In [15]:
import torch
import numpy as np

In [2]:
x = torch.ones(3, requires_grad=True)

In [3]:
x

tensor([1., 1., 1.], requires_grad=True)

In [4]:
y = x + 2

In [5]:
y

tensor([3., 3., 3.], grad_fn=<AddBackward0>)

In [6]:
z = y * y
z
z = z.mean()
print(z)

tensor(9., grad_fn=<MeanBackward0>)


In [7]:
z.backward()

In [8]:
print(x.grad)

tensor([2., 2., 2.])


In [9]:
x

tensor([1., 1., 1.], requires_grad=True)

In [10]:
y = x.detach()

In [11]:
y

tensor([1., 1., 1.])

In [12]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([3., 3., 3.])


In [13]:
x.requires_grad_(False)

tensor([1., 1., 1.])

In [25]:
weights = torch.ones(3, requires_grad=True)

In [26]:
for epoch in range(4):

    model_output = (weights * 3).sum()

    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()


tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
