In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision
import numpy as np
import math

In [2]:
class WineDataset(Dataset):
    def __init__(self, transform = None):
        df = np.loadtxt("wine.csv", delimiter=",", dtype=np.float32, skiprows=1)
        print(df.shape)
        self.n_samples = df.shape[0]
        self.x = df[:, 1:]
        self.y = df[:, [0]]

        self.transform = transform
    
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if(self.transform):
            sample = self.transform(sample)
        
        return sample
    
    def __len__(self):
        return self.n_samples


In [7]:
class Totensor:
    def __call__(self, sample):
        inputs, labels = sample
        inputs = torch.from_numpy(inputs)
        labels = torch.from_numpy(labels)

        return inputs, labels


df = WineDataset(transform=Totensor())

(178, 14)


In [8]:
print(df.x.shape, df.y.shape)
print(df[0])

(178, 13) (178, 1)
(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))


In [9]:
print(df[0])

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))


In [10]:
itr = 2
sample = len(df)
batch_size = math.ceil(sample / 4)


train_loader = DataLoader(dataset=df, batch_size=4, shuffle=True)
print(train_loader)

dataiter = iter(train_loader)
print(dataiter)
data = next(dataiter)
print(data)
features, labels = data
print(features, labels)

[tensor([[1.2820e+01, 3.3700e+00, 2.3000e+00, 1.9500e+01, 8.8000e+01, 1.4800e+00,
         6.6000e-01, 4.0000e-01, 9.7000e-01, 1.0260e+01, 7.2000e-01, 1.7500e+00,
         6.8500e+02],
        [1.2530e+01, 5.5100e+00, 2.6400e+00, 2.5000e+01, 9.6000e+01, 1.7900e+00,
         6.0000e-01, 6.3000e-01, 1.1000e+00, 5.0000e+00, 8.2000e-01, 1.6900e+00,
         5.1500e+02],
        [1.2520e+01, 2.4300e+00, 2.1700e+00, 2.1000e+01, 8.8000e+01, 2.5500e+00,
         2.2700e+00, 2.6000e-01, 1.2200e+00, 2.0000e+00, 9.0000e-01, 2.7800e+00,
         3.2500e+02],
        [1.3270e+01, 4.2800e+00, 2.2600e+00, 2.0000e+01, 1.2000e+02, 1.5900e+00,
         6.9000e-01, 4.3000e-01, 1.3500e+00, 1.0200e+01, 5.9000e-01, 1.5600e+00,
         8.3500e+02]]), tensor([[3.],
        [3.],
        [2.],
        [3.]])]
tensor([[1.2820e+01, 3.3700e+00, 2.3000e+00, 1.9500e+01, 8.8000e+01, 1.4800e+00,
         6.6000e-01, 4.0000e-01, 9.7000e-01, 1.0260e+01, 7.2000e-01, 1.7500e+00,
         6.8500e+02],
        [1.2530e+01

In [11]:
for epoch in range(itr):
    for i, (inputs, label) in enumerate(train_loader):

        if (i + 1) % 5 == 0:
            print(f"epoch: {i + 1} / {batch_size}, ")

epoch: 5 / 45, 
epoch: 10 / 45, 
epoch: 15 / 45, 
epoch: 20 / 45, 
epoch: 25 / 45, 
epoch: 30 / 45, 
epoch: 35 / 45, 
epoch: 40 / 45, 
epoch: 45 / 45, 
epoch: 5 / 45, 
epoch: 10 / 45, 
epoch: 15 / 45, 
epoch: 20 / 45, 
epoch: 25 / 45, 
epoch: 30 / 45, 
epoch: 35 / 45, 
epoch: 40 / 45, 
epoch: 45 / 45, 
