In [1]:
import torch

In [5]:
x = torch.ones(2, 2, 2)

In [6]:
x

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [7]:
y = torch.rand(2,2)

In [8]:
y

tensor([[0.6568, 0.6309],
        [0.1730, 0.9689]])

In [9]:
y = torch.tensor([1, 1])

In [10]:
y

tensor([1, 1])

In [11]:
z = torch.mul(x, y)

In [12]:
z

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [13]:
z = torch.div(x, y)

In [14]:
z

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [15]:
import numpy as np

In [47]:
z = np.array(z)
x = torch.rand(2 ,2)

In [48]:
x

tensor([[0.8930, 0.9230],
        [0.0408, 0.0500]])

In [49]:
y = x.view(-1, 1)

In [50]:
y

tensor([[0.8930],
        [0.9230],
        [0.0408],
        [0.0500]])

In [51]:
y = y.numpy()

In [52]:
y

array([[0.8930282 ],
       [0.9229778 ],
       [0.04078203],
       [0.04996485]], dtype=float32)

In [54]:
x += 1

In [55]:
x

tensor([[1.8930, 1.9230],
        [1.0408, 1.0500]])

In [56]:
y

array([[1.8930283],
       [1.9229778],
       [1.040782 ],
       [1.0499649]], dtype=float32)

In [60]:
x = torch.from_numpy(y)

In [61]:
x

tensor([[1.8930],
        [1.9230],
        [1.0408],
        [1.0500]])